### ISSUE TITLE
Race condition during blue-green deploys

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/route-emitter#8]
## The problem

We have deployed open source Cloud Foundry v265, upgrading from v257. We fully automate the deployment of applications using the blue-green-deployment plugin. There was zero downtime with CF v257, but now with CF v265 there is up to 60 seconds where requests to the app are responded to with a status code of 404.

## Steps to reproduce

* Deploy Cloud Foundry v265
* Deploy an application
* Set up a `curl` to monitor the app:

  ```
  while true; do curl -s -o /dev/null -w "%{http_code} " https://${APP_NAME}.${APP_DOMAIN} -k; date; sleep 1; done | tee /tmp/bgd.out
  ```

* Do a blue-green deploy using this [example script](https://gist.github.com/henrytk/3a45e082b5713c268b5eea03dd922cfa).

You should see 404s returned after the unmapping of the route from the old application for up to 60 seconds.

Add a sleep of 60 seconds before the unmapping of the route from the old app and the problem goes away.

## Debugging

Because the downtime is always less than 60 seconds I believe the state in BBS is correct and on the bulk update the problem gets fixed. Therefore, the route-emitter is somehow unregistering the route from the new app instead of the old app. I've confirmed this by tailing the logs of the GoRouter and I can see the unregistration messages being logged.

We compiled the route-emitter for every commit between that in Diego v1.18.1 and v1.19.0 and tracked it down to this commit: [`525adefba513e0825545ecc4b40db19c36edbd9c`](https://github.com/cloudfoundry/route-emitter/commit/525adefba513e0825545ecc4b40db19c36edbd9c). The commit was too big to do further debugging, so we rely on a fix from the maintainers.

## Versions affected

cf-release v265
diego-release v1.19.0

**Comment by ematpl** [comment]
Thanks, @henrytk! Looks like this routing issue caused problems with the unmap/map sequence at https://gist.github.com/henrytk/3a45e082b5713c268b5eea03dd922cfa#file-cf-blue-green-deployment-L8-L9, and we believe that this is now fixed with https://github.com/cloudfoundry/route-emitter/commit/f95c6093df6494bbbfebe2440538583fef2244da as part of https://www.pivotaltracker.com/story/show/148602639. That fix will be in the next final release of Diego final release, which I expect to cut shortly.

Best,
Eric, CF Diego PM
